---
aliases:
  - name: ll
    cmd: ls -l
    complete: false
  - name: la
    cmd: ls -a
    complete: false
  - name: rc
    cmd: echo $?
    complete: false
  - name: arsync
    cmd: rsync -havuHP --stat
    complete: false
  - name: sl
    cmd: systemctl
    complete: false
  - name: jl
    cmd: journalctl
    complete: false
  - name: apb
    cmd: ansible-playbook
    complete: false
  - name: adoc
    cmd: ansible-doc
    complete: false
  - name: acfg
    cmd: ansible-config
    complete: false
  - name: avlt
    cmd: ansible-vault
    complete: false
  - name: agal
    cmd: ansible-galaxy
    complete: false
  - name: alint
    cmd: ansible-lint
    complete: false
  - name: python
    cmd: python3
    complete: false
  - name: pypile
    cmd: python3 -m py_compile
    complete: false
  - name: pyvenv
    cmd: python3 -m venv
    complete: false

