---
- name: Setup UX preferences
  hosts: localhost
  become: false
  gather_facts: true
  connection: local
  vars_files:
    - vars/escape_sequences.yml
    - vars/bash_prompts.yml
    - vars/bash_aliases.yml
  vars:
    add_situational_functions: false
    remove_old: false
  tasks:
    - name: Set facts about user
      set_fact:
        u:
          name: "{{ ansible_facts['user_id'] }}"
          home: "{{ ansible_facts['user_dir'] }}"

    - name: Create home .bashrc.d inclusion directory
      file:
        path: "{{ u.home }}/.bashrc.d"
        state: directory
        owner: "{{ u.name }}"
    
    - name: Add inclusion logic for custom bash files
      blockinfile:
        block: |
          for x in ~/.bashrc.d/*.bash; do
            . "$x"
          done
        path: "{{ u.home }}/.bashrc"
        state: present

    - name: Find old bashrc configs
      find:
        paths: "{{ u.home }}/.bashrc.d"
        patterns: 'bash_*'
        file_type: file
      register: old_bash
      when: remove_old | bool

    - name: Remove old bashrc configs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_bash.files }}"
      when: remove_old | bool
                
    - name: Add bashrc template files
      template:
        src: templates/{{ item }}.j2
        dest: "{{ u.home }}/.bashrc.d/{{ item }}"
        backup: true
      loop:
        - prompt.bash
        - aliases.bash
        - functions.bash
        - variables.bash

    - name: Create nvim configuration base directory
      file:
        path: "{{ u.home }}/.config/nvim"
        state: directory

    - name: Add vimrc template file
      template:
        src: templates/vimrc.j2
        dest: "{{ u.home }}/.vimrc"
        backup: true
      loop:
        - "{{ u.home }}/.vimrc"
        - "{{ u.home }}/.config/nvim/init.vim"
    
