---
bash:
  user: '\u'
  host: '\h'
  date: '\d'
  time_hm: '\A'
  time_hms: '\t'
  full_cwd: '\w'
  base_cwd: '\W'

ansi_esc: '\[\033[{}m\]'

ansi:
  style:
    reset: '0'
    bold: '1'
    dim: '2'
    italic: '3'
    underline: '4'
    slow_blink: '5'
    fast_blink: '6'
    reverse: '7'
    hidden: '8'
    strikethru: '9'

  fg:
    black: '30'
    red: '31'
    green: '32'
    yellow: '33'
    blue: '34'
    magenta: '35'
    cyan: '36'
    white: '37'
    default: '39'
    bright_black: '90'
    bright_red: '91'
    bright_green: '92'
    bright_yellow: '93'
    bright_blue: '94'
    bright_magenta: '95'
    bright_cyan: '96'
    bright_white: '97'

  bg:
    black: '40'
    red: '41'
    green: '42'
    yellow: '43'
    blue: '44'
    magenta: '45'
    cyan: '46'
    white: '47'
    default: '49'
    bright_black: '100'
    bright_red: '101'
    bright_green: '102'
    bright_yellow: '103'
    bright_blue: '104'
    bright_magenta: '105'
    bright_cyan: '106'
    bright_white: '107'

  256:
    # Standard colors: 0-15
    black: '0'
    maroon: '1'
    green: '2'
    olive: '3'
    navy: '4'
    purple: '5'
    teal: '6'
    silver: '7'
    grey: '8'
    red: '9'
    lime: '10'
    yellow: '11'
    blue: '12'
    fuchsia: '13'
    aqua: '14'
    white: '15'

    # 6x6x6 RGB color cube: 16-231
    grey0: '16'
    navy_blue: '17'
    dark_blue: '18'
    blue3_a: '19'
    blue3_b: '20'
    blue1: '21'
    dark_green: '22'
    deep_sky_blue4_a: '23'
    deep_sky_blue4_b: '24'
    deep_sky_blue4_c: '25'
    dodger_blue3: '26'
    dodger_blue2: '27'
    green4: '28'
    spring_green4: '29'
    turquoise4: '30'
    deep_sky_blue3_a: '31'
    deep_sky_blue3_b: '32'
    dodger_blue1: '33'
    green3_a: '34'
    spring_green3_a: '35'
    dark_cyan: '36'
    light_sea_green: '37'
    deep_sky_blue2: '38'
    deep_sky_blue1: '39'
    green3_b: '40'
    spring_green3_b: '41'
    spring_green2_a: '42'
    cyan3: '43'
    dark_turquoise: '44'
    turquoise2: '45'
    green1: '46'
    spring_green2_b: '47'
    spring_green1: '48'
    medium_spring_green: '49'
    cyan2: '50'
    cyan1: '51'
    dark_red_a: '52'
    deep_pink4_a: '53'
    purple4_a: '54'
    purple4_b: '55'
    purple3: '56'
    blue_violet: '57'
    orange4_a: '58'
    grey37: '59'
    medium_purple4: '60'
    slate_blue3_a: '61'
    slate_blue3_b: '62'
    royal_blue1: '63'
    chartreuse4: '64'
    dark_sea_green4_a: '65'
    pale_turquoise4: '66'
    steel_blue: '67'
    steel_blue3: '68'
    cornflower_blue: '69'
    chartreuse3_a: '70'
    dark_sea_green4_b: '71'
    cadet_blue_a: '72'
    cadet_blue_b: '73'
    sky_blue3: '74'
    steel_blue1_a: '75'
    chartreuse3_b: '76'
    pale_green3_a: '77'
    sea_green3: '78'
    aquamarine3: '79'
    medium_turquoise: '80'
    steel_blue1_b: '81'
    chartreuse2_a: '82'
    sea_green2: '83'
    sea_green1_a: '84'
    sea_green1_b: '85'
    aquamarine1_a: '86'
    dark_slate_gray2: '87'
    dark_red_b: '88'
    deep_pink4_b: '89'
    dark_magenta_a: '90'
    dark_magenta_b: '91'
    dark_violet_a: '92'
    purple_a: '93'
    orange4_b: '94'
    light_pink4: '95'
    plum4: '96'
    medium_purple3_a: '97'
    medium_purple3_b: '98'
    slate_blue1: '99'
    yellow4_a: '100'
    wheat4: '101'
    grey53: '102'
    light_slate_grey: '103'
    medium_purple: '104'
    light_slate_blue: '105'
    yellow4_b: '106'
    dark_olive_green3_a: '107'
    dark_sea_green: '108'
    light_sky_blue3_a: '109'
    light_sky_blue3_b: '110'
    sky_blue2: '111'
    chartreuse2_b: '112'
    dark_olive_green3_b: '113'
    pale_green3_b: '114'
    dark_sea_green3_a: '115'
    dark_slate_gray3: '116'
    sky_blue1: '117'
    chartreuse1: '118'
    light_green_a: '119'
    light_green_b: '120'
    pale_green1_a: '121'
    aquamarine1_b: '122'
    dark_slate_gray1: '123'
    red3_a: '124'
    deep_pink4_c: '125'
    medium_violet_red: '126'
    magenta3_a: '127'
    dark_violet_b: '128'
    purple_b: '129'
    dark_orange3_a: '130'
    indian_red_a: '131'
    hot_pink3_a: '132'
    medium_orchid3: '133'
    medium_orchid: '134'
    medium_purple2_a: '135'
    dark_goldenrod: '136'
    light_salmon3_a: '137'
    rosy_brown: '138'
    grey63: '139'
    medium_purple2_b: '140'
    medium_purple1: '141'
    gold3_a: '142'
    dark_khaki: '143'
    navajo_white3: '144'
    grey69: '145'
    light_steel_blue3: '146'
    light_steel_blue: '147'
    yellow3_a: '148'
    dark_olive_green3_c: '149'
    dark_sea_green3_b: '150'
    dark_sea_green2_a: '151'
    light_cyan3: '152'
    light_sky_blue1: '153'
    green_yellow: '154'
    dark_olive_green2: '155'
    pale_green1_b: '156'
    dark_sea_green2_b: '157'
    dark_sea_green1_a: '158'
    pale_turquoise1: '159'
    red3_b: '160'
    deep_pink3_a: '161'
    deep_pink3_b: '162'
    magenta3_b: '163'
    magenta3_c: '164'
    magenta2_a: '165'
    dark_orange3_b: '166'
    indian_red_b: '167'
    hot_pink3_b: '168'
    hot_pink2: '169'
    orchid: '170'
    medium_orchid1_a: '171'
    orange3: '172'
    light_salmon3_b: '173'
    light_pink3: '174'
    pink3: '175'
    plum3: '176'
    violet: '177'
    gold3_b: '178'
    light_goldenrod3: '179'
    tan: '180'
    misty_rose3: '181'
    thistle3: '182'
    plum2: '183'
    yellow3_b: '184'
    khaki3: '185'
    light_goldenrod2_a: '186'
    light_yellow3: '187'
    grey84: '188'
    light_steel_blue1: '189'
    yellow2: '190'
    dark_olive_green1_a: '191'
    dark_olive_green1_b: '192'
    dark_sea_green1_b: '193'
    honeydew2: '194'
    light_cyan1: '195'
    red1: '196'
    deep_pink2: '197'
    deep_pink1_a: '198'
    deep_pink1_b: '199'
    magenta2_b: '200'
    magenta1: '201'
    orange_red1: '202'
    indian_red1_a: '203'
    indian_red1_b: '204'
    hot_pink_a: '205'
    hot_pink_b: '206'
    medium_orchid1_b: '207'
    dark_orange: '208'
    salmon1: '209'
    light_coral: '210'
    pale_violet_red1: '211'
    orchid2: '212'
    orchid1: '213'
    orange1: '214'
    sandy_brown: '215'
    light_salmon1: '216'
    light_pink1: '217'
    pink1: '218'
    plum1: '219'
    gold1: '220'
    light_goldenrod2_b: '221'
    light_goldenrod2_c: '222'
    navajo_white1: '223'
    misty_rose1: '224'
    thistle1: '225'
    yellow1: '226'
    light_goldenrod1: '227'
    khaki1: '228'
    wheat1: '229'
    cornsilk1: '230'
    grey100: '231'

    # Grayscale ramp: 232-255
    grey3: '232'
    grey7: '233'
    grey11: '234'
    grey15: '235'
    grey19: '236'
    grey23: '237'
    grey27: '238'
    grey30: '239'
    grey35: '240'
    grey39: '241'
    grey42: '242'
    grey46: '243'
    grey50: '244'
    grey54: '245'
    grey58: '246'
    grey62: '247'
    grey66: '248'
    grey70: '249'
    grey74: '250'
    grey78: '251'
    grey82: '252'
    grey85: '253'
    grey89: '254'
    grey93: '255'

